services:
  - type: web
    name: cloudy-server
    env: node
    buildCommand: yarn install
    startCommand: yarn start
    repo: https://github.com/lightdash/lightdash-cloud-announcer.git
    region: oregon
    plan: standard
    branch: main
    healthCheckPath: /healthz
    envVars:
      - key: PG_CONNECTION_STRING
        fromDatabase:
          name: cloudy-db
          property: connectionString
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_CLIENT_ID
        sync: false
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: SLACK_STATE_SECRET
        sync: false
      - key: SLACK_AUTHORIZED_TEAMS
        value: "T0163M87MB9,T03942PB7E3"
      - key: SITE_ENV
        value: "https://cloudy-server.onrender.com"
      - key: RUDDERSTACK_WRITE_KEY
        sync: false
      - key: RUDDERSTACK_DATAPLANE_URL
        value: https://analytics.lightdash.com
      - key: GITHUB_WEBHOOKS_SECRET
        sync: false
      - key: GITHUB_ACCESS_TOKEN
        sync: false

databases:
  - name: cloudy-db
    region: oregon
    ipAllowList: []


